### PR TITLE
Small refactoring and commenting on functions file.

### PR DESCRIPTION
**Pull request by olivernybroe**
Made some small refactorings and added some  comments to the functions file, hope you can use it!

I recommend you add an SQL dump or something like that of the database, so contributors can test if it works.

### CODE REVIEW

**Comment by mcb2003** [comment]
Just reviewing your pull request now. 

 By the way, there is a database dump. It’s in the mysql-file branch.  I’ve considered making it a separate repository, do you think that will help?

**Comment by olivernybroe** [comment]
@mcb2003 my bad, didn't see the branch.

Maybe add it to the contribution guide, that should be enough. No need for a repository for that alone.

**Comment by mcb2003** [comment]
Good idea. I’m merging this PR.

**Comment by mcb2003** [comment]
All done.  The websites also updated. I’ve also added the mysql-file Branch to the readme file in the table of branches. Good suggestion! I’d completely forgotten about it.

**Pull request merged**
